### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Heisenberg1997** [YuQWorks/YuQ-Mirai-Demo#4]
大佬，我这个说找不到这个类，我看了一下在main里面import了一个com.icecreamqaq.yuq.mirai.YuQMiraiStart,项目里面好像并没有找到这个，这个需要在哪下载么还是什么，这个要放在那里啊，谢谢大佬！

**Comment by IceCream-QAQ** [comment]
尝试重新拉取 Maven 或是 Gradle 依赖。

**Comment by Heisenberg1997** [comment]
大哥，留个联系方式么，有一些问题想问问大哥，我q1415637345，vx15032137383，谢谢谢谢大哥了

**Comment by Heisenberg1997** [comment]
这个com.icecreamqaq.yuq.mirai.YuQMiraiStart来自于jar包么 就是需要通过Maven重新加载依赖来找到这个com的， 我看了一下仓库，com里有IceCreamQAQ没有小写的那个

**Comment by IceCream-QAQ** [comment]
class com.icecreamqaq.yuq.mirai.YuQMiraiStart 来自库 com.IceCreamQAQ.YuQ.YuQ-Mirai。

联系方式考虑：QQ 群：696129128

**Comment by maojunhat** [comment]
同样的问题 有解决办法吗？
