### ISSUE TITLE
在运行的时候报错

### ISSUE THREAD

**Issue by Qubik65536** [YuQWorks/YuQ-Mirai-Demo#6]
第一次使用YuQ，希望可以使用Demo进行学习，可是在运行的时候报错：
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=�)
编译&运行环境：IntelliJ IDEA，Java 1.8，Gradle
是否可以通过升级某些依赖解决呢？

**Comment by Qubik65536** [comment]
我是直接使用IDEA clone，Gradle配置，Java 1.8，在YuQ.properties里填入QQ号和密码之后build，随后右键Run Start运行的

**Comment by yimkong** [comment]
我用maven也是一样的提示，启动报错，版本过低，实际上是最新版本

**Comment by JackuXL** [comment]
同

**Comment by aecra** [comment]
同，你们问题解决了吗？

**Comment by IceCream-QAQ** [comment]
关于这个问题，统一更新 YuQ-Mirai 依赖到 0.1.0.0-DEV14 版本。

**Comment by DDreame** [comment]
附加回答，检查账号密码是否错误。WrongPasswordException

**Comment by Qubik65536** [comment]
> 附加回答，检查账号密码是否错误。WrongPasswordException

已确定账号密码没有错误



> 关于这个问题，统一更新 YuQ-Mirai 依赖到 0.1.0.0-DEV14 版本。

已通过更新依赖解决，感谢！
