### ISSUE TITLE
Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)

### ISSUE THREAD

**Issue by JackuXL** [YuQWorks/YuQ-Mirai-Demo#7]
Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)

**Comment by IceCream-QAQ** [comment]
关于这个问题，统一更新 YuQ-Mirai 依赖到 0.1.0.0-DEV14 版本。

**Comment by criusKer** [comment]
> 关于这个问题，统一更新 YuQ-Mirai 依赖到 0.1.0.0-DEV14 版本。

我更新了还是有这个问题，产生这个问题的原因是啥，我大号和新号会出现，另一个小号却没事

**Comment by IceCream-QAQ** [comment]
> > 关于这个问题，统一更新 YuQ-Mirai 依赖到 0.1.0.0-DEV14 版本。
> 
> 我更新了还是有这个问题，产生这个问题的原因是啥，我大号和新号会出现，另一个小号却没事

明天百年纪念日，所以风控特别严。
